/*
 * This file is generated by jOOQ.
 */
package jhi.seams.server.database.codegen;


import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeamsDb extends SchemaImpl {

    private static final long serialVersionUID = -971726983;

    /**
     * The reference instance of <code>seams_db</code>
     */
    public static final SeamsDb SEAMS_DB = new SeamsDb();

    /**
     * No further instances allowed
     */
    private SeamsDb() {
        super("seams_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
// @formatter:on
}
