/*
 * This file is generated by jOOQ.
 */
package jhi.seams.server.database.codegen.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.seams.server.database.codegen.enums.MeasurementsMeasurementType;
import jhi.seams.server.database.codegen.tables.Measurements;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeasurementsRecord extends UpdatableRecordImpl<MeasurementsRecord> implements Record8<Integer, Integer, Integer, Integer, BigDecimal, MeasurementsMeasurementType, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1540777177;

    /**
     * Setter for <code>seams_db.measurements.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>seams_db.measurements.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>seams_db.measurements.dataset_id</code>.
     */
    public void setDatasetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>seams_db.measurements.dataset_id</code>.
     */
    public Integer getDatasetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>seams_db.measurements.trait_id</code>.
     */
    public void setTraitId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>seams_db.measurements.trait_id</code>.
     */
    public Integer getTraitId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>seams_db.measurements.trait_unit_id</code>.
     */
    public void setTraitUnitId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>seams_db.measurements.trait_unit_id</code>.
     */
    public Integer getTraitUnitId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>seams_db.measurements.measurement</code>.
     */
    public void setMeasurement(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>seams_db.measurements.measurement</code>.
     */
    public BigDecimal getMeasurement() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>seams_db.measurements.measurement_type</code>.
     */
    public void setMeasurementType(MeasurementsMeasurementType value) {
        set(5, value);
    }

    /**
     * Getter for <code>seams_db.measurements.measurement_type</code>.
     */
    public MeasurementsMeasurementType getMeasurementType() {
        return (MeasurementsMeasurementType) get(5);
    }

    /**
     * Setter for <code>seams_db.measurements.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>seams_db.measurements.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>seams_db.measurements.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>seams_db.measurements.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, BigDecimal, MeasurementsMeasurementType, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, BigDecimal, MeasurementsMeasurementType, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Measurements.MEASUREMENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Measurements.MEASUREMENTS.DATASET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Measurements.MEASUREMENTS.TRAIT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Measurements.MEASUREMENTS.TRAIT_UNIT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Measurements.MEASUREMENTS.MEASUREMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MeasurementsMeasurementType> field6() {
        return Measurements.MEASUREMENTS.MEASUREMENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Measurements.MEASUREMENTS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Measurements.MEASUREMENTS.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTraitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTraitUnitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getMeasurement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsMeasurementType component6() {
        return getMeasurementType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDatasetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTraitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTraitUnitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getMeasurement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsMeasurementType value6() {
        return getMeasurementType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value2(Integer value) {
        setDatasetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value3(Integer value) {
        setTraitId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value4(Integer value) {
        setTraitUnitId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value5(BigDecimal value) {
        setMeasurement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value6(MeasurementsMeasurementType value) {
        setMeasurementType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value7(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord value8(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeasurementsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, BigDecimal value5, MeasurementsMeasurementType value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeasurementsRecord
     */
    public MeasurementsRecord() {
        super(Measurements.MEASUREMENTS);
    }

    /**
     * Create a detached, initialised MeasurementsRecord
     */
    public MeasurementsRecord(Integer id, Integer datasetId, Integer traitId, Integer traitUnitId, BigDecimal measurement, MeasurementsMeasurementType measurementType, Timestamp createdOn, Timestamp updatedOn) {
        super(Measurements.MEASUREMENTS);

        set(0, id);
        set(1, datasetId);
        set(2, traitId);
        set(3, traitUnitId);
        set(4, measurement);
        set(5, measurementType);
        set(6, createdOn);
        set(7, updatedOn);
    }
// @formatter:on
}
