/*
 * This file is generated by jOOQ.
 */
package jhi.seams.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Arrays;

import javax.annotation.Generated;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewDatasetMeta implements Serializable {

    private static final long serialVersionUID = -1368198350;

    private Integer   datasetId;
    private String    datasetName;
    private String    siteName;
    private Double    latitude;
    private Double    longitude;
    private String    tillage;
    private String    fertilizer;
    private String    herbicide;
    private String    farmManagement;
    private String    weedCover;
    private String    disease;
    private String    pests;
    private String    soilHealth;
    private String    biodiversity;
    private String    cropPurpose;
    private Timestamp sowingDate;
    private Timestamp harvestDate;
    private String[]  componentNames;
    private Integer[] componentIds;

    public ViewDatasetMeta() {}

    public ViewDatasetMeta(ViewDatasetMeta value) {
        this.datasetId = value.datasetId;
        this.datasetName = value.datasetName;
        this.siteName = value.siteName;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.tillage = value.tillage;
        this.fertilizer = value.fertilizer;
        this.herbicide = value.herbicide;
        this.farmManagement = value.farmManagement;
        this.weedCover = value.weedCover;
        this.disease = value.disease;
        this.pests = value.pests;
        this.soilHealth = value.soilHealth;
        this.biodiversity = value.biodiversity;
        this.cropPurpose = value.cropPurpose;
        this.sowingDate = value.sowingDate;
        this.harvestDate = value.harvestDate;
        this.componentNames = value.componentNames;
        this.componentIds = value.componentIds;
    }

    public ViewDatasetMeta(
        Integer   datasetId,
        String    datasetName,
        String    siteName,
        Double    latitude,
        Double    longitude,
        String    tillage,
        String    fertilizer,
        String    herbicide,
        String    farmManagement,
        String    weedCover,
        String    disease,
        String    pests,
        String    soilHealth,
        String    biodiversity,
        String    cropPurpose,
        Timestamp sowingDate,
        Timestamp harvestDate,
        String[]  componentNames,
        Integer[] componentIds
    ) {
        this.datasetId = datasetId;
        this.datasetName = datasetName;
        this.siteName = siteName;
        this.latitude = latitude;
        this.longitude = longitude;
        this.tillage = tillage;
        this.fertilizer = fertilizer;
        this.herbicide = herbicide;
        this.farmManagement = farmManagement;
        this.weedCover = weedCover;
        this.disease = disease;
        this.pests = pests;
        this.soilHealth = soilHealth;
        this.biodiversity = biodiversity;
        this.cropPurpose = cropPurpose;
        this.sowingDate = sowingDate;
        this.harvestDate = harvestDate;
        this.componentNames = componentNames;
        this.componentIds = componentIds;
    }

    public Integer getDatasetId() {
        return this.datasetId;
    }

    public void setDatasetId(Integer datasetId) {
        this.datasetId = datasetId;
    }

    public String getDatasetName() {
        return this.datasetName;
    }

    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName;
    }

    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    public Double getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getTillage() {
        return this.tillage;
    }

    public void setTillage(String tillage) {
        this.tillage = tillage;
    }

    public String getFertilizer() {
        return this.fertilizer;
    }

    public void setFertilizer(String fertilizer) {
        this.fertilizer = fertilizer;
    }

    public String getHerbicide() {
        return this.herbicide;
    }

    public void setHerbicide(String herbicide) {
        this.herbicide = herbicide;
    }

    public String getFarmManagement() {
        return this.farmManagement;
    }

    public void setFarmManagement(String farmManagement) {
        this.farmManagement = farmManagement;
    }

    public String getWeedCover() {
        return this.weedCover;
    }

    public void setWeedCover(String weedCover) {
        this.weedCover = weedCover;
    }

    public String getDisease() {
        return this.disease;
    }

    public void setDisease(String disease) {
        this.disease = disease;
    }

    public String getPests() {
        return this.pests;
    }

    public void setPests(String pests) {
        this.pests = pests;
    }

    public String getSoilHealth() {
        return this.soilHealth;
    }

    public void setSoilHealth(String soilHealth) {
        this.soilHealth = soilHealth;
    }

    public String getBiodiversity() {
        return this.biodiversity;
    }

    public void setBiodiversity(String biodiversity) {
        this.biodiversity = biodiversity;
    }

    public String getCropPurpose() {
        return this.cropPurpose;
    }

    public void setCropPurpose(String cropPurpose) {
        this.cropPurpose = cropPurpose;
    }

    public Timestamp getSowingDate() {
        return this.sowingDate;
    }

    public void setSowingDate(Timestamp sowingDate) {
        this.sowingDate = sowingDate;
    }

    public Timestamp getHarvestDate() {
        return this.harvestDate;
    }

    public void setHarvestDate(Timestamp harvestDate) {
        this.harvestDate = harvestDate;
    }

    public String[] getComponentNames() {
        return this.componentNames;
    }

    public void setComponentNames(String... componentNames) {
        this.componentNames = componentNames;
    }

    public Integer[] getComponentIds() {
        return this.componentIds;
    }

    public void setComponentIds(Integer... componentIds) {
        this.componentIds = componentIds;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewDatasetMeta (");

        sb.append(datasetId);
        sb.append(", ").append(datasetName);
        sb.append(", ").append(siteName);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(tillage);
        sb.append(", ").append(fertilizer);
        sb.append(", ").append(herbicide);
        sb.append(", ").append(farmManagement);
        sb.append(", ").append(weedCover);
        sb.append(", ").append(disease);
        sb.append(", ").append(pests);
        sb.append(", ").append(soilHealth);
        sb.append(", ").append(biodiversity);
        sb.append(", ").append(cropPurpose);
        sb.append(", ").append(sowingDate);
        sb.append(", ").append(harvestDate);
        sb.append(", ").append(Arrays.toString(componentNames));
        sb.append(", ").append(Arrays.toString(componentIds));

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
