/*
 * This file is generated by jOOQ.
 */
package jhi.seams.server.database.codegen.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jhi.seams.server.database.codegen.SeamsDb;
import jhi.seams.server.database.codegen.enums.MeasurementsMeasurementType;
import jhi.seams.server.database.codegen.tables.records.MeasurementsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measurements extends TableImpl<MeasurementsRecord> {

    private static final long serialVersionUID = 1878287871;

    /**
     * The reference instance of <code>seams_db.measurements</code>
     */
    public static final Measurements MEASUREMENTS = new Measurements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MeasurementsRecord> getRecordType() {
        return MeasurementsRecord.class;
    }

    /**
     * The column <code>seams_db.measurements.id</code>.
     */
    public final TableField<MeasurementsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>seams_db.measurements.dataset_id</code>.
     */
    public final TableField<MeasurementsRecord, Integer> DATASET_ID = createField("dataset_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>seams_db.measurements.trait_id</code>.
     */
    public final TableField<MeasurementsRecord, Integer> TRAIT_ID = createField("trait_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>seams_db.measurements.trait_unit_id</code>.
     */
    public final TableField<MeasurementsRecord, Integer> TRAIT_UNIT_ID = createField("trait_unit_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>seams_db.measurements.measurement</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> MEASUREMENT = createField("measurement", org.jooq.impl.SQLDataType.DECIMAL(12, 6).nullable(false), this, "");

    /**
     * The column <code>seams_db.measurements.measurement_type</code>.
     */
    public final TableField<MeasurementsRecord, MeasurementsMeasurementType> MEASUREMENT_TYPE = createField("measurement_type", org.jooq.impl.SQLDataType.VARCHAR(4).nullable(false).defaultValue(org.jooq.impl.DSL.inline("mono", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(jhi.seams.server.database.codegen.enums.MeasurementsMeasurementType.class), this, "");

    /**
     * The column <code>seams_db.measurements.created_on</code>.
     */
    public final TableField<MeasurementsRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>seams_db.measurements.updated_on</code>.
     */
    public final TableField<MeasurementsRecord, Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>seams_db.measurements</code> table reference
     */
    public Measurements() {
        this(DSL.name("measurements"), null);
    }

    /**
     * Create an aliased <code>seams_db.measurements</code> table reference
     */
    public Measurements(String alias) {
        this(DSL.name(alias), MEASUREMENTS);
    }

    /**
     * Create an aliased <code>seams_db.measurements</code> table reference
     */
    public Measurements(Name alias) {
        this(alias, MEASUREMENTS);
    }

    private Measurements(Name alias, Table<MeasurementsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Measurements(Name alias, Table<MeasurementsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SeamsDb.SEAMS_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MeasurementsRecord, Integer> getIdentity() {
        return Internal.createIdentity(jhi.seams.server.database.codegen.tables.Measurements.MEASUREMENTS, jhi.seams.server.database.codegen.tables.Measurements.MEASUREMENTS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MeasurementsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(jhi.seams.server.database.codegen.tables.Measurements.MEASUREMENTS, "KEY_measurements_PRIMARY", jhi.seams.server.database.codegen.tables.Measurements.MEASUREMENTS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MeasurementsRecord>> getKeys() {
        return Arrays.<UniqueKey<MeasurementsRecord>>asList(
              Internal.createUniqueKey(jhi.seams.server.database.codegen.tables.Measurements.MEASUREMENTS, "KEY_measurements_PRIMARY", jhi.seams.server.database.codegen.tables.Measurements.MEASUREMENTS.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Measurements as(String alias) {
        return new Measurements(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Measurements as(Name alias) {
        return new Measurements(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Measurements rename(String name) {
        return new Measurements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Measurements rename(Name name) {
        return new Measurements(name, null);
    }
// @formatter:on
}
