/*
 * This file is generated by jOOQ.
 */
package jhi.seams.server.database.codegen.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jhi.seams.server.database.codegen.SeamsDb;
import jhi.seams.server.database.codegen.tables.records.UnitsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Units extends TableImpl<UnitsRecord> {

    private static final long serialVersionUID = -1912702217;

    /**
     * The reference instance of <code>seams_db.units</code>
     */
    public static final Units UNITS = new Units();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UnitsRecord> getRecordType() {
        return UnitsRecord.class;
    }

    /**
     * The column <code>seams_db.units.id</code>.
     */
    public final TableField<UnitsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>seams_db.units.name</code>.
     */
    public final TableField<UnitsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>seams_db.units.description</code>.
     */
    public final TableField<UnitsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.units.created_on</code>.
     */
    public final TableField<UnitsRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>seams_db.units.updated_on</code>.
     */
    public final TableField<UnitsRecord, Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>seams_db.units</code> table reference
     */
    public Units() {
        this(DSL.name("units"), null);
    }

    /**
     * Create an aliased <code>seams_db.units</code> table reference
     */
    public Units(String alias) {
        this(DSL.name(alias), UNITS);
    }

    /**
     * Create an aliased <code>seams_db.units</code> table reference
     */
    public Units(Name alias) {
        this(alias, UNITS);
    }

    private Units(Name alias, Table<UnitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Units(Name alias, Table<UnitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SeamsDb.SEAMS_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UnitsRecord, Integer> getIdentity() {
        return Internal.createIdentity(jhi.seams.server.database.codegen.tables.Units.UNITS, jhi.seams.server.database.codegen.tables.Units.UNITS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UnitsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(jhi.seams.server.database.codegen.tables.Units.UNITS, "KEY_units_PRIMARY", jhi.seams.server.database.codegen.tables.Units.UNITS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UnitsRecord>> getKeys() {
        return Arrays.<UniqueKey<UnitsRecord>>asList(
              Internal.createUniqueKey(jhi.seams.server.database.codegen.tables.Units.UNITS, "KEY_units_PRIMARY", jhi.seams.server.database.codegen.tables.Units.UNITS.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Units as(String alias) {
        return new Units(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Units as(Name alias) {
        return new Units(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Units rename(String name) {
        return new Units(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Units rename(Name name) {
        return new Units(name, null);
    }
// @formatter:on
}
