/*
 * This file is generated by jOOQ.
 */
package jhi.seams.server.database.codegen.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.seams.server.binding.IntArrayBinding;
import jhi.seams.server.binding.StringArrayBinding;
import jhi.seams.server.database.codegen.SeamsDb;
import jhi.seams.server.database.codegen.tables.records.ViewDatasetMetaRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewDatasetMeta extends TableImpl<ViewDatasetMetaRecord> {

    private static final long serialVersionUID = 785331605;

    /**
     * The reference instance of <code>seams_db.view_dataset_meta</code>
     */
    public static final ViewDatasetMeta VIEW_DATASET_META = new ViewDatasetMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewDatasetMetaRecord> getRecordType() {
        return ViewDatasetMetaRecord.class;
    }

    /**
     * The column <code>seams_db.view_dataset_meta.dataset_id</code>.
     */
    public final TableField<ViewDatasetMetaRecord, Integer> DATASET_ID = createField("dataset_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.dataset_name</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> DATASET_NAME = createField("dataset_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.site_name</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> SITE_NAME = createField("site_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.latitude</code>.
     */
    public final TableField<ViewDatasetMetaRecord, Double> LATITUDE = createField("latitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.longitude</code>.
     */
    public final TableField<ViewDatasetMetaRecord, Double> LONGITUDE = createField("longitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.tillage</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> TILLAGE = createField("tillage", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.fertilizer</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> FERTILIZER = createField("fertilizer", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.herbicide</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> HERBICIDE = createField("herbicide", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.farm_management</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> FARM_MANAGEMENT = createField("farm_management", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.weed_cover</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> WEED_COVER = createField("weed_cover", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.disease</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> DISEASE = createField("disease", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.pests</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> PESTS = createField("pests", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.soil_health</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> SOIL_HEALTH = createField("soil_health", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.biodiversity</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> BIODIVERSITY = createField("biodiversity", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.crop_purpose</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String> CROP_PURPOSE = createField("crop_purpose", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.sowing_date</code>.
     */
    public final TableField<ViewDatasetMetaRecord, Timestamp> SOWING_DATE = createField("sowing_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.harvest_date</code>.
     */
    public final TableField<ViewDatasetMetaRecord, Timestamp> HARVEST_DATE = createField("harvest_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>seams_db.view_dataset_meta.component_names</code>.
     */
    public final TableField<ViewDatasetMetaRecord, String[]> COMPONENT_NAMES = createField("component_names", org.jooq.impl.DefaultDataType.getDefaultDataType("\"seams\".\"view_dataset_meta_component_names\""), this, "", new StringArrayBinding());

    /**
     * The column <code>seams_db.view_dataset_meta.component_ids</code>.
     */
    public final TableField<ViewDatasetMetaRecord, Integer[]> COMPONENT_IDS = createField("component_ids", org.jooq.impl.DefaultDataType.getDefaultDataType("\"seams\".\"view_dataset_meta_component_ids\""), this, "", new IntArrayBinding());

    /**
     * Create a <code>seams_db.view_dataset_meta</code> table reference
     */
    public ViewDatasetMeta() {
        this(DSL.name("view_dataset_meta"), null);
    }

    /**
     * Create an aliased <code>seams_db.view_dataset_meta</code> table reference
     */
    public ViewDatasetMeta(String alias) {
        this(DSL.name(alias), VIEW_DATASET_META);
    }

    /**
     * Create an aliased <code>seams_db.view_dataset_meta</code> table reference
     */
    public ViewDatasetMeta(Name alias) {
        this(alias, VIEW_DATASET_META);
    }

    private ViewDatasetMeta(Name alias, Table<ViewDatasetMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewDatasetMeta(Name alias, Table<ViewDatasetMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SeamsDb.SEAMS_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewDatasetMeta as(String alias) {
        return new ViewDatasetMeta(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewDatasetMeta as(Name alias) {
        return new ViewDatasetMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewDatasetMeta rename(String name) {
        return new ViewDatasetMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewDatasetMeta rename(Name name) {
        return new ViewDatasetMeta(name, null);
    }
// @formatter:on
}
