/*
 * This file is generated by jOOQ.
 */
package jhi.seams.server.database.codegen.tables;


import jhi.seams.server.binding.StringArrayBinding;
import jhi.seams.server.database.codegen.SeamsDb;
import jhi.seams.server.database.codegen.enums.ViewDatasetDataMeasurementType;
import jhi.seams.server.database.codegen.tables.records.ViewDatasetDataRecord;
import org.jooq.*;
import org.jooq.impl.*;

import javax.annotation.Generated;
import java.sql.Timestamp;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewDatasetData extends TableImpl<ViewDatasetDataRecord> {

    private static final long serialVersionUID = -746980941;

    /**
     * The reference instance of <code>seams_db.view_dataset_data</code>
     */
    public static final ViewDatasetData VIEW_DATASET_DATA = new ViewDatasetData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewDatasetDataRecord> getRecordType() {
        return ViewDatasetDataRecord.class;
    }

    /**
     * The column <code>seams_db.view_dataset_data.dataset_id</code>.
     */
    public final TableField<ViewDatasetDataRecord, Integer> DATASET_ID = createField("dataset_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>seams_db.view_dataset_data.dataset_name</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> DATASET_NAME = createField("dataset_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>seams_db.view_dataset_data.site_name</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> SITE_NAME = createField("site_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>seams_db.view_dataset_data.latitude</code>.
     */
    public final TableField<ViewDatasetDataRecord, Double> LATITUDE = createField("latitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.longitude</code>.
     */
    public final TableField<ViewDatasetDataRecord, Double> LONGITUDE = createField("longitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.tillage</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> TILLAGE = createField("tillage", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>seams_db.view_dataset_data.fertilizer</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> FERTILIZER = createField("fertilizer", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.herbicide</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> HERBICIDE = createField("herbicide", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.farm_management</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> FARM_MANAGEMENT = createField("farm_management", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.weed_cover</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> WEED_COVER = createField("weed_cover", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.disease</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> DISEASE = createField("disease", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.pests</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> PESTS = createField("pests", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.soil_health</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> SOIL_HEALTH = createField("soil_health", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.biodiversity</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> BIODIVERSITY = createField("biodiversity", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.cover_crop</code>.
     */
    public final TableField<ViewDatasetDataRecord, String> COVER_CROP = createField("cover_crop", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.sowing_date</code>.
     */
    public final TableField<ViewDatasetDataRecord, Timestamp> SOWING_DATE = createField("sowing_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.harvest_date</code>.
     */
    public final TableField<ViewDatasetDataRecord, Timestamp> HARVEST_DATE = createField("harvest_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.components</code>.
     */
    public final TableField<ViewDatasetDataRecord, String[]> COMPONENTS = createField("components", org.jooq.impl.DefaultDataType.getDefaultDataType("\"seams\".\"view_dataset_data_components\""), this, "", new StringArrayBinding());

    /**
     * The column <code>seams_db.view_dataset_data.sowing_rate</code>.
     */
    public final TableField<ViewDatasetDataRecord, Double> SOWING_RATE = createField("sowing_rate", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.yield</code>.
     */
    public final TableField<ViewDatasetDataRecord, Double> YIELD = createField("yield", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>seams_db.view_dataset_data.measurement_type</code>.
     */
    public final TableField<ViewDatasetDataRecord, ViewDatasetDataMeasurementType> MEASUREMENT_TYPE = createField("measurement_type", org.jooq.impl.SQLDataType.VARCHAR(4).nullable(false).defaultValue(org.jooq.impl.DSL.inline("mono", org.jooq.impl.SQLDataType.VARCHAR)).asEnumDataType(jhi.seams.server.database.codegen.enums.ViewDatasetDataMeasurementType.class), this, "");

    /**
     * Create a <code>seams_db.view_dataset_data</code> table reference
     */
    public ViewDatasetData() {
        this(DSL.name("view_dataset_data"), null);
    }

    /**
     * Create an aliased <code>seams_db.view_dataset_data</code> table reference
     */
    public ViewDatasetData(String alias) {
        this(DSL.name(alias), VIEW_DATASET_DATA);
    }

    /**
     * Create an aliased <code>seams_db.view_dataset_data</code> table reference
     */
    public ViewDatasetData(Name alias) {
        this(alias, VIEW_DATASET_DATA);
    }

    private ViewDatasetData(Name alias, Table<ViewDatasetDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewDatasetData(Name alias, Table<ViewDatasetDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SeamsDb.SEAMS_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewDatasetData as(String alias) {
        return new ViewDatasetData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewDatasetData as(Name alias) {
        return new ViewDatasetData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewDatasetData rename(String name) {
        return new ViewDatasetData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewDatasetData rename(Name name) {
        return new ViewDatasetData(name, null);
    }
// @formatter:on
}
